using System;
using System.Collections.Generic;
using System.Linq;
using BudgetTracker.Controllers.ViewModels.Payment;
using BudgetTracker.Model;

namespace BudgetTracker.Controllers.ViewModels.Widgets
{
    public class ExpensesWidgetViewModel : WidgetViewModel
    {
        public ExpensesWidgetViewModel(WidgetModel model, ObjectRepository repository, int? period) : base(model, new ExpensesWidgetSettings(model.Properties.ToDictionary(v=>v.Key, v=>v.Value)))
        {
            Period = Math.Max(1, period ?? 1);
            ExpenseSettings = (ExpensesWidgetSettings) Settings;
            var payments = repository.Set<PaymentModel>()
                .Where(v => IsApplicable(v.When, Period) && v.Ccy == ExpenseSettings.Currency &&
                            v.Kind == PaymentKind.Expense && !v.Autogenerated)
                .Select(v => new PaymentViewModel(v))
                .ToList();
            
            
            var data = payments.OrderByDescending(v => -v.Amount).Select(v =>
            {
                var value = (int) -v.Amount;

                var name = "";
                if (!string.IsNullOrWhiteSpace(v.Category))
                    name = v.Category;
                else if (!string.IsNullOrWhiteSpace(v.Debt))
                    name = v.Debt;
                else
                {
                    name = v.What;
                    if (name.Length > 32)
                        name = name.Remove(31) + "…";
                }

                return new {name, value};
            }).ToList();

            var toRemove = data.Skip(11).ToList();
            data = data.Take(11).ToList();

            if (toRemove.Any())
            {
                toRemove.ForEach(x => data.Remove(x));
            }
            
            var values = data.Select(v => v.value).ToList();
            var names = data.Select(v =>
            {
                if (v == data.Last())
                    return "Остальное";

                return v.name;
            }).ToList();

            Values = values;
            Names = names;
        }

        public List<string> Names { get; set; }

        public List<int> Values { get; set; }

        public ExpensesWidgetSettings ExpenseSettings { get; set; }

        public override int Columns => 8;
        public override int Rows => 2;
        public int Period { get; set; }
    }
}