using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using BudgetTracker.Controllers.ViewModels.Payment;
using BudgetTracker.Model;

namespace BudgetTracker.Controllers.ViewModels.Widgets
{
    public class ExpensesWidgetViewModel : WidgetViewModel
    {
        public ExpensesWidgetViewModel(WidgetModel model, ObjectRepository repository, int? period) : base(model, new ExpensesWidgetSettings(model.Properties.ToDictionary(v=>v.Key, v=>v.Value)))
        {
            Period = Math.Max(1, period ?? 1);
            ExpenseSettings = (ExpensesWidgetSettings) Settings;
            var payments = repository.Set<PaymentModel>()
                .Where(v => IsApplicable(v.When, Period) && v.Ccy == ExpenseSettings.Currency &&
                            v.Kind == PaymentKind.Expense && !v.Autogenerated)
                .Select(v => new PaymentViewModel(v))
                .ToList();
            
            
            var data = payments.OrderByDescending(v => -v.Amount).ToList();

            var toRemove = data.Skip(11).ToList();
            data = data.Take(11).ToList();

            if (toRemove.Any())
            {
                toRemove.ForEach(x => data.Remove(x));
            }
    
            var values = data.Select(v => (int)-v.Amount).ToList();
            var names = data.Select(v =>
            {
                if (v == data.Last())
                    return "Остальное";
        
                if (!string.IsNullOrWhiteSpace(v.Category))
                    return v.Category;
                if (!string.IsNullOrWhiteSpace(v.Debt))
                    return v.Debt;
                if (v.What.Length > 32)
                    return v.What.Remove(31) + "...";
                return v.What;
            }).ToList();

            Values = values;
            Names = names;
        }

        public List<string> Names { get; set; }

        public List<int> Values { get; set; }

        public ExpensesWidgetSettings ExpenseSettings { get; set; }

        public override int Columns => 8;
        public override int Rows => 2;
        public int Period { get; set; }
    }
}