// autogenerated
import './services/Rest';

export interface MoneyColumnMetadataJsModel {
   AccountName: string;
}

export interface SystemInfo {
   IsProduction: boolean;
   LaunchTime: string;
   Stats: string;
   CurrentVersion: string;
   LatestVersion: string;
   HasNewerVersion: boolean;
}

export interface TableJsModel {
   Vm: any;
   Providers: string[];
   Provider: string;
}

export class SystemController {
    static async SiteInfo(): Promise<SystemInfo> { return window.rest.cachedQuery(`/System/SiteInfo`); };
}

export class TableController {
    static async IndexJson(provider: string): Promise<TableJsModel> { return window.rest.query(`/Table/IndexJson?provider=` + provider + ``); };
}

